// Generated by GENERATOR: 11/29/2020, 12:23:56 PM
import { Module } from '@nestjs/common';
import { TypegooseModule } from 'nestjs-typegoose';

import { DictionaryService } from './dictionary/dictionary.service';
import { DictionaryResolver } from './dictionary/graphql/dictionary.resolver';
import { Dictionary } from './dictionary/models/dictionary.model';
import { ElementService } from './element/element.service';
import { ElementResolver } from './element/graphql/element.resolver';
import { Element } from './element/models/element.model';


@Module({
    imports: [
        TypegooseModule.forFeature([Dictionary, Element,])
    ],
    providers: [
        DictionaryService,
        DictionaryResolver,
        ElementService,
        ElementResolver,
    ],
    exports: [
        DictionaryService,
        ElementService,
    ],
})
export class DictionaryModule { }
