import { MaxLength } from 'class-validator';

import { BaseDto, ON_CREATE } from '../../../../base/base.dto';
import { Element } from './element.model';

// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

export class ElementDto extends BaseDto<Element> {
  @MaxLength(50, ON_CREATE)
  name: string

}
