// Generated by GENERATOR: 11/29/2020, 12:23:56 PM
import { modelOptions, prop } from '@typegoose/typegoose';

import { MongoBaseModel } from '../../../../base/typegoose/base.model';



@modelOptions({ schemaOptions: { collection: "dictionary" } })
export class Dictionary extends MongoBaseModel {

  @prop({ required: true, maxlength: 100 })
  public name: string

  @prop({ required: true, type: () => String })
  public letters: string[]
}
