import { ArrayMinSize, IsArray, MaxLength } from 'class-validator';

import { BaseDto, ON_CREATE } from '../../../../base/base.dto';
import { Dictionary } from './dictionary.model';

// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

export class DictionaryDto extends BaseDto<Dictionary> {
  @MaxLength(100, ON_CREATE)
  name: string

  @IsArray(ON_CREATE)
  @ArrayMinSize(1, ON_CREATE)
  letters: string[]

}
