import { Field, ID, InputType, ObjectType, PartialType } from '@nestjs/graphql';

// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

@InputType()
export class CreateDictionaryInput {
  name: string
  @Field(type => [String])
  letters: string[]
}

@InputType()
export class UpdateDictionaryInput extends PartialType(CreateDictionaryInput) {
  @Field(type => ID)
  _id: string;
}

@ObjectType()
export class Dictionary {
  @Field(type => ID)
  _id: string;
  name: string
  letters: string
}
