import { Args, Mutation, Resolver } from '@nestjs/graphql';

import { DictionaryService } from '../dictionary.service';
import { Json } from './../../../../shared/graphql/scalars/json.scalar';
import { CreateDictionaryInput, Dictionary } from './dictionary.schema';

// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

@Resolver(of => Dictionary)
export class DictionaryResolver {
    constructor(private service: DictionaryService) { }

    @Mutation(returns => Json)
    createDictionary(@Args('input', { type: () => CreateDictionaryInput }) input) {
        return this.service.create(input)
    }
}
