import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';

import { Json } from './../../../../shared/graphql/scalars/json.scalar';
import { ElementService } from './../element.service';
import { CreateElementInput, Element, GetManyElements } from './element.schema';

// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

@Resolver(of => Element)
export class ElementResolver {

    constructor(private elementService: ElementService) { }

    @Query(returns => GetManyElements)
    getElements() {
        return this.elementService.getMany({ paginationInput: { page: 1, limit: 1000 } })
    }

    @Mutation(returns => Json)
    async createElement(
        @Args('input', { type: () => CreateElementInput }) input
    ) {
        return await this.elementService.create(input)
    }
}
