#************************************ Shared by all schemas ************************************
scalar Date
scalar object

input PaginationInput {
  page: Int 
  limit: Int!
  skip:Int
  startingAfter:String
}

type Pagination {
  totalElements: Int
  hasNextPage: Boolean
  nextPage: Int
  previousPage: Int
  lastPage: Int
}

type objectResponse {
  message: String
  status: Int
  data:object
}

type ValidationResult {
  idValid: Boolean!
  errors: String
}

input GetManyInput{
  paginationInput: PaginationInput!
  params: Params!
}

input Params {
    find: object
    populate: object
    aggregate: [object]
    select: String
    distinct: String
    sort: String
}
#************************************ End Shared ************************************
