// Generated by GENERATOR: 11/29/2020, 12:23:56 PM

    import { Injectable } from '@nestjs/common';
    import { Dictionary } from './models/dictionary.model';
    import { BaseService } from '../../../base/typegoose/base.service';

    @Injectable()
    export class DictionaryService extends BaseService<Dictionary>(Dictionary) { }
